CREATE SCHEMA IF NOT EXISTS BIBLIOTECA;

CREATE TABLE LIBRO
( 
ID_LIBRO INT NOT NULL,
TITOLO TEXT NOT NULL,
ISBN VARCHAR(13) NOT NULL,
LINGUA TEXT NOT NULL,
ANNO_PUBBLICAZIONE VARCHAR(4) NOT NULL,
IDSUCCURSALE INT NOT NULL,

PRIMARY KEY (ID_LIBRO),
FOREIGN KEY (IDSUCCURSALE) REFERENCES SUCCURSALE (ID_SUCCURSALE)
ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE AUTORE 
(
ID_AUTORE INT NOT NULL,
NOME VARCHAR(100) NOT NULL,
COGNOME VARCHAR(100) NOT NULL,
DATA_NASCITA DATE NOT NULL,
LUOGO_NASCITA VARCHAR(50) NOT NULL,

PRIMARY KEY (ID_AUTORE)
);

CREATE TABLE SUCCURSALE
(
ID_SUCCURSALE INT NOT NULL,
NOME VARCHAR(100) NOT NULL,
INDIRIZZO VARCHAR(100) NOT NULL,
CITTA VARCHAR(50) NOT NULL,

PRIMARY KEY (ID_SUCCURSALE)
);

CREATE TABLE UTENTE
(
NUMERO_MATRICOLA INT NOT NULL,
TELEFONO CHAR(10) NOT NULL,
INDIRIZZO_ABITAZIONE VARCHAR(100) NOT NULL,
NOME VARCHAR(20) NOT NULL,
COGNOME VARCHAR(20) NOT NULL,

PRIMARY KEY (NUMERO_MATRICOLA)
);

CREATE TABLE PRENDE
(
ID_PRESTITO INT NOT NULL,
IDLIBRO INT NOT NULL,
MATRICOLA INT NOT NULL,
DATA_USCITA DATE NOT NULL,
DATA_RESTITUZIONE DATE NOT NULL,

PRIMARY KEY (ID_PRESTITO),
FOREIGN KEY (IDLIBRO) REFERENCES LIBRO (ID_LIBRO),
FOREIGN KEY (MATRICOLA) REFERENCES UTENTE (NUMERO_MATRICOLA)
ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE LIBRO_AUTORE
(
ID_LIBRI_AUTORI INT NOT NULL,
IDLIBRO INT NOT NULL,
IDAUTORE INT NOT NULL,

PRIMARY KEY (ID_LIBRI_AUTORI),
FOREIGN KEY (IDLIBRO) REFERENCES LIBRO (ID_LIBRO),
FOREIGN KEY (IDAUTORE) REFERENCES AUTORE (ID_AUTORE)
ON DELETE NO ACTION ON UPDATE CASCADE
);

